pipeline {
    agent {
        docker {
            image 'maven:3.9-eclipse-temurin-21'
            args '-v $HOME/.m2:/root/.m2'
        }
    }
    stages {
        stage('Checkout') {
            steps {
                checkout scm
            }
        }
        stage('Build') {
            steps {
                dir('starter'){
                    sh 'mvn -B clean package'
                }
            }
        }
        stage('Test') {
            steps {
                dir('starter'){
                    sh 'mvn -B test'
                }
                
            }
            post {
                always {
                    junit 'starter/target/surefire-reports/*.xml'
                }
            }
        }
        stage('Archive') {
            steps {
                archiveArtifacts artifacts: 'starter/target/*.jar', fingerprint: true
            }
        }
    }
}
