pipeline {
    agent any
    tools {
        maven 'Maven3'
    }
    stages {
        stage('Checkout') {
            steps {
                checkout scmGit(
                    branches: [[name: '*/main']],
                    userRemoteConfigs: [[url: 'https://github.com/Celina-Shrestha-LEAP/jenkins-demo.git']],
                    gitTool: 'Default'
                )
            }
        }
        stage('Build') {
            steps {
                dir(starter){
                    sh 'mvn -B clean package'
                }
            }
        }
        stage('Test') {
            steps {
                dir(starter){
                    sh 'mvn -B test'
                }
                
            }
            post {
                always {
                    junit 'target/test-reports/*.xml'
                }
            }
        }
        stage('Archive') {
            steps {
                archiveArtifacts artifacts: 'target/*.jar', fingerprint: true
            }
        }
    }
}
